name: Release Growthackr (.zips)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      releaseTitle: { description: 'Release title' }
      releaseDescription: { description: 'Release description' }

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🚧 Zip Debug and Stable releases
        run: |
          cd dist
          zip -r ../Growthackr-Debug.zip debug
          zip -r ../Growthackr-Stable.zip release
          cd ..

      - name: 📝 Get latest commit message for release notes
        id: changelog
        run: |
          echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT

      - name: 🚀 Create GitHub Release and upload Debug and Stable zip assets
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          name: ${{ github.event.inputs.releaseTitle || format('Growthackr {0}', github.ref_name) }}
          body: ${{ github.event.inputs.releaseDescription || steps.changelog.outputs.message }}
          files: |
            Growthackr-Debug.zip
            Growthackr-Stable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
